### ISSUE TITLE
Can't build due due to lack of int to complex double promotion

### ISSUE THREAD

**Issue by obackhouse** [hgaburton/libgnme#3]
I can't seem to build the package due to errors such as

```
libgnme/wick/wick_rscf.C:70:18: error: no match for ‘operator*’ (operand types are ‘int’ and ‘std::complex<double>’)
     Pb *= parity * m_orb.m_redS * m_orb.m_redS * sa;
```

Presumably my compiler versions are not supporting automatic promotion in this way - I am using `gcc==7.2.0`, `CMake==3.20.3` and have tried passing `std=c14` and `std=c++14`. Am I missing something?

**Comment by hgaburton** [comment]
This is an issue with the GCC compiler and should now be resolved by explicitly including the type conversion.
